# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: downloading ubuntu-16.04-server-cloudimg-amd64-disk1.img
  get_url:
    url: http://uec-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
    dest: /home/{{ regular_system_user }}/svauto/downloads/ubuntu-16.04-server-cloudimg-amd64-disk1.img
    mode: 0640
  ignore_errors: yes

- name: downloading ubuntu-14.04-server-cloudimg-amd64-disk1.img
  get_url:
    url: http://uec-images.ubuntu.com/releases/14.04/14.04.4/ubuntu-14.04-server-cloudimg-amd64-disk1.img
    dest: /home/{{ regular_system_user }}/svauto/downloads/ubuntu-14.04-server-cloudimg-amd64-disk1.img
    mode: 0640
  ignore_errors: yes

- name: downloading ubuntu-12.04-server-cloudimg-amd64-disk1.img
  get_url:
    url: http://uec-images.ubuntu.com/releases/12.04.4/12.04.5/ubuntu-12.04-server-cloudimg-amd64-disk1.img
    dest: /home/{{ regular_system_user }}/svauto/downloads/ubuntu-12.04-server-cloudimg-amd64-disk1.img
    mode: 0640
  ignore_errors: yes

- name: downloading debian-8.7.0-openstack-amd64.qcow2
  get_url:
    url: http://cdimage.debian.org/cdimage/openstack/current/debian-8.7.0-openstack-amd64.qcow2
    dest: /home/{{ regular_system_user }}/svauto/downloads/debian-8.6.1-openstack-amd64.qcow2
    mode: 0640
  ignore_errors: yes

- name: downloading CentOS-7-x86_64-GenericCloud.qcow2c
  get_url:
    url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2c
    dest: /home/{{ regular_system_user }}/svauto/downloads/CentOS-7-x86_64-GenericCloud.qcow2c
    mode: 0640
  ignore_errors: yes

- name: downloading CentOS-6-x86_64-GenericCloud.qcow2c
  get_url:
    url: http://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2c
    dest: /home/{{ regular_system_user }}/svauto/downloads/CentOS-6-x86_64-GenericCloud.qcow2c
    mode: 0640
  ignore_errors: yes

- name: downloading cirros-0.3.4-x86_64-disk.img
  get_url:
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    dest: /home/{{ regular_system_user }}/svauto/downloads/cirros-0.3.4-x86_64-disk.img
    mode: 0640
  ignore_errors: yes
