# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reference:
# https://docs.openstack.org/project-install-guide/telemetry/ocata/install-base-ubuntu.html

- name: Installing Ceilometer
  apt: name={{item}} state=latest
  with_items:
    - ceilometer-collector
    - ceilometer-agent-central
    - ceilometer-agent-notification
  notify: restart-ceilometer


- name: Updating ceilometer.conf
  template: src={{ os_release }}/ceilometer.conf
        dest=/etc/ceilometer/ceilometer.conf
        owner=ceilometer
        group=ceilometer
        mode=0640
        backup=yes
  notify: restart-ceilometer


- name: Populating Ceilometer Database
  shell: ceilometer-upgrade --skip-metering-database


- meta: flush_handlers
