# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reference:
# https://docs.openstack.org/developer/senlin/install.html

- include: openstack-senlin-init.yml
  when: deployment_mode == 'yes'


- name: Installing Senlin
  apt: name={{item}} state=latest
  with_items:
    - senlin-api
    - senlin-engine
  notify: restart-senlin


- name: Updating senlin.conf
  template: src={{ os_release }}/senlin.conf
        dest=/etc/senlin/senlin.conf
        owner=senlin
        group=senlin
        mode=0640
        backup=yes
  when: item.os_project == "senlin"
  with_items: '{{mysql_databases}}'
  notify: restart-senlin


- name: Populating Senlin Database
  shell: su -s /bin/sh -c "senlin-manage db_sync" senlin


- meta: flush_handlers
